version: 2

jobs:
  build_and_test:
    docker:
      - image: framgia/laravel-workspace
    steps:
      - checkout
      - run: cp web/.env.example web/.env

      # composer cache
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum "composer.lock" }}
      - run:  
          name: Install composer
          command: |
            cd web
            composer install
      - save_cache:
          key: vendor-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # run test
      - run: phpcs --standard=Framgia app